# Bitcoin IP banlist dataset
# This file contains a list of entities and their IP addresses that could be
# malicious actors on the Bitcoin network.

[[entities]]
name = "LinkingLion"
added = 2023-03-27
tags = []
description = """
This entity connects from four IP address ranges to listening Bitcoin nodes
using fake user agents. While many of the connections are short-lived, some
listen for transaction announcements. This might allow the entity to link
transactions to IP addresses.

The IP address ranges are annouced by Lionlink Networks (AS54098):

- `162.218.65.0/24`
- `209.222.252.0/24`
- `91.198.115.0/24`
- `2604:d500:4:1::/64`

Some of these IP ranges have been making connections to Bitcoin nodes since
at least 2018 and connect to nodes on the Monero network too. It's unclear if
they are VPN endpoints. The entity could be a blockchain analysis company
enhancing their products with the collected data.

More details: https://b10c.me/observations/06-linkinglion
"""
ips = [
  "162.218.65.0/24",
  "209.222.252.0/24",
  "91.198.115.0/24",
  "2604:d500:4:1::/64",
]

[[entities]]
name = "LinodeGhost"
added = 2026-06-25
tags = []
description = """
This entity with user agent /Satoshi:27.0.0/ on Linode/AS63949 only gossips itself.
2,006 IP addresses were gosipped in total but half of these IP addresses seem dead.
The reachable ones always have these characteristics:
- report a block height of 0
- answer every GETADDR request with exactly 256 addresses. each address in the response is:
    - timestamped to the present
    - belongs to the fleet itself

This fleet did not exist in 2024. Across addrman snapshots on peer.observer they occupy
around 0.2% of the new table but around 6% of the tried table, rising to 10% in some snapshots.
When crawling the network these are by far the most frequently seen IPv4 addresses in GETADDR responses.
Of the 5,000 most-advertised addresses, almost all of which are onion,
only nine are IPv4 and all nine belong to this fleet.

More details: https://bnoc.xyz/t/small-getaddr-responses-from-897-nodes-satoshi-27-0-0-on-as63949/121/1
"""
ips_file = "ips/linodeghost.txt"
